apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
        - name: configmaps-secret
          image: ritikaxg/configmaps-secrets:1
          ports:
            - containerPort: 3000
          env:
            - name: PORT  
              valueFrom:
                configMapKeyRef:
                  name: config-backend
                  key: port
          volumeMounts: # This container has a volume mount # all keys at backend-secret will be mounted as files at mountPath
            - name: env-file
              readOnly: true
              mountPath: "/app/secret" # you can't put "/app" here since it will replace the existing "/app" containing ur app files with "/app" containing only ".env" file so u need to mount .env file in seperate dir
      volumes: # These volumes will become available to all containers defined here
        - name: env-file # name of volume
          secret: # pick from 'backend-secret'
            secretName: backend-secret 
      